name: Your CI Workflow

on: ["push"]

jobs:
  job1:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/') # Run job1 only when a tag is pushed
    steps:
      - name: print
        run: |
          echo $GITHUB_REF
