name: Your CI Workflow

on: ["push"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Build Verilator
        run: |
          # Prerequisites:
          sudo apt-get -y install git help2man perl python3 make autoconf g++ flex bison ccache
          sudo apt-get -y install libgoogle-perftools-dev numactl perl-doc libunwind-dev
          sudo apt-get -y install libfl2  # Ubuntu only (ignore if gives error)
          sudo apt-get -y install libfl-dev  # Ubuntu only (ignore if gives error)
          sudo apt-get -y install zlibc zlib1g zlib1g-dev  # Ubuntu only (ignore if gives error)
          
          git clone https://github.com/verilator/verilator   # Only first time
          
          # Every time you need to build:
          unsetenv VERILATOR_ROOT  # For csh; ignore error if on bash
          unset VERILATOR_ROOT  # For bash
          cd verilator
          git pull         # Make sure git repository is up-to-date
          git tag          # See what versions exist
          #git checkout master      # Use development branch (e.g. recent bug fixes)
          #git checkout stable      # Use most recent stable release
          #git checkout v{version}  # Switch to specified release version
          
          autoconf         # Create ./configure script
          ./configure      # Configure and create Makefile
          make -j 4  # Build Verilator itself (if error, try just 'make')
          sudo make install
