name: Your CI Workflow

on: ["push"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Build Verilator
        run: |
          wget http://mirrors.kernel.org/ubuntu/pool/universe/v/verilator/verilator_5.012-1_amd64.deb
          sudo dpkg -i verilator_5.012-1_amd64.deb
          
